
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-env0-app0-user
  namespace: app-0
spec:
  dnsNames:
    - user.app0.env0.luojm.com
  secretName: tls-env0-app0-user
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer