apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1 
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: registry.cn-shanghai.aliyuncs.com/niceice/user
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: aliyun-credentials-sh
