
mutation createTables {
  addcontactsrequest: createTable(
    keyspaceName:"app_0_contacts",
    tableName:"add_contacts_request",
    partitionKeys: [ 
      { name: "id", type: {basic: TEXT} }
    ]
    clusteringKeys: [
    ]
    values: [
      { name: "user_id", type: {basic: TEXT} }
      { name: "contacts_id", type: {basic: TEXT} }
      { name: "remark_name", type: {basic: TEXT} }
      { name: "update_time", type: {basic: TIMESTAMP} }
    ]
  )
}

mutation dropTable {
  dropaddcontactsrequest: dropTable(
    keyspaceName: "app_0_contacts"
    tableName: "add_contacts_request"
    ifExists: true
  )
}