
mutation createTables {
  addcontactsapply: createTable(
    keyspaceName:"app_0_contacts",
    tableName:"add_contacts_apply",
    partitionKeys: [ 
      { name: "id", type: {basic: TEXT} }
    ]
    clusteringKeys: [
    ]
    values: [
      { name: "user_id", type: {basic: TEXT} }
      { name: "contacts_id", type: {basic: TEXT} }
      { name: "remark_name", type: {basic: TEXT} }
      { name: "message", type: {basic: TEXT} }
      { name: "update_time", type: {basic: TIMESTAMP} }
    ]
  )
}

mutation createContactsIdIndex{
  createNameIndex: createIndex(
    keyspaceName: "app_0_contacts"
    tableName: "add_contacts_apply"
    columnName: "contacts_id"
    ifNotExists: true
  )
}

mutation dropTable {
  dropaddcontactsapply: dropTable(
    keyspaceName: "app_0_contacts"
    tableName: "add_contacts_apply"
    ifExists: true
  )
}


mutation alterTableAdd{
  alterTableAdd(keyspaceName: "app_0_contacts", tableName:"add_contacts_apply", toAdd: { name: "message", type: {basic: TEXT}})
}
