// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auth struct {
	AuthID     string `json:"auth_id"`
	AuthIDType string `json:"auth_id_type"`
	UserID     string `json:"user_id"`
}

type Result struct {
	Auth         *Auth  `json:"auth"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}
