
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-contacts
  namespace: app-0
data:
  config-contacts.yml: |+
    listen_address: ":80"
    path: /
    db_name: contacts
    db_pool_connections_num: 4
    db_config_file_path: "/etc/app-0/config-crdb/config-crdb.yml"
    pulsar_config_file_path: "/etc/app-0/config-pulsar/config-pulsar.yml"
    pulsar_topic: "tenant-0/contacts/add_contacts_apply"
    public_key_file_path: "/etc/app-0/secret-jwt/jwt-publickey"
    private_key_file_path: "/etc/app-0/secret-jwt/jwt-privatekey"

