apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-env0-app0-contacts
  namespace: app-0
spec:
  dnsNames:
    - contacts.app0.env0.luojm.com
  secretName: tls-env0-app0-contacts
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: contacts
  namespace: app-0
spec:
  entryPoints:
    - websecure
  tls: 
    secretName: tls-env0-app0-contacts
  routes:
    - match: Host(`contacts.app0.env0.luojm.com`) 
      kind: Rule
      services:
      - name: contacts
        kind: Service
        namespace: app-0
        port: 80

