apiVersion: v1
kind: Service
metadata:
  name: contacts
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: contacts
  sessionAffinity: None
  type: NodePort

