design:

add_contacts_apply: contacts_id: k, update_time: c_desc, user_id: c_asc
contacts: user_id: k, contacts_id: k
contacts_by_remakr_name: user_id: k, remark_name: c_asc, contacts_id: c_asc


-------

###########



mutation createKeyspace{
  contacts: createKeyspace(
    name: "app_0_contacts"
    ifNotExists: true
    datacenters: [
      { name: "dc1", replicas: 3 }
    ]
)
}

mutation createTables {
  addcontactsapply: createTable(
    keyspaceName:"app_0_contacts",
    tableName:"add_contacts_apply",
    partitionKeys: [ 
      { name: "contacts_id", type: {basic: TEXT} }
    ]
    clusteringKeys: [
      { name: "update_time", type: {basic: TIMESTAMP}, order: "DESC" }
      { name: "user_id", type: {basic: TEXT} }
    ]
    values: [
      { name: "id", type: {basic: TEXT} }
      { name: "remark_name", type: {basic: TEXT} }
      { name: "message", type: {basic: TEXT} }
    ]
  )
}

# mutation createIndex{
#   createIndex: createIndex(
#     keyspaceName: "app_0_contacts"
#     tableName: "add_contacts_apply"
#     columnName: "id"
#     ifNotExists: true
#   )
# }

mutation dropTable {
  dropaddcontactsapply: dropTable(
    keyspaceName: "app_0_contacts"
    tableName: "add_contacts_apply"
    ifExists: true
  )
}

mutation alterTableAdd{
  alterTableAdd(keyspaceName: "app_0_contacts", tableName:"add_contacts_apply", toAdd: { name: "reply", type: {basic: TEXT}})
}
