// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Avatar struct {
	PreSignedURL       string `json:"preSignedUrl"`
	AnonymousAccessURL string `json:"anonymousAccessUrl"`
}

type User struct {
	ID   string  `json:"id"`
	Name *string `json:"name"`
	Data *string `json:"data"`
}
