// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ContactsConnection struct {
	TotalCount int       `json:"totalCount"`
	Edges      []*Edge   `json:"edges"`
	PageInfo   *PageInfo `json:"pageInfo"`
}

type Edge struct {
	Node   *Node  `json:"node"`
	Cursor string `json:"cursor"`
}

type Node struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor"`
	HasNextPage bool    `json:"hasNextPage"`
}

type PaginationContacts struct {
	ID                 string              `json:"id"`
	ContactsConnection *ContactsConnection `json:"contactsConnection"`
}
