apiVersion: v1
kind: Service
metadata:
  name: pubsub-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pubsub-service
  sessionAffinity: None
  type: NodePort

