apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: app-0
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 2 
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: registry.cn-shanghai.aliyuncs.com/logic-base/auth:0.0.1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret-cassandra
          mountPath: /etc/app-0
          readOnly: true
        - name: config
          mountPath: /etc/app-0
          readOnly: true
        - name: config-auth
          mountPath: /etc/app-0
          readOnly: true
      volumes:
        - name: secret-cassandra
          secret:
            secretName: secret-cassandra
            optional: false # 默认设置，意味着 secret 必须已经存在
        - name: config
          configMap:
            name: config
        - name: config-auth
          configMap:
            name: config-auth

        
