
FROM golang

ENV APP_PATH=/opt/niceice/p2p-signaling-service
WORKDIR $APP_PATH

COPY ./service/. /opt/niceice/p2p-signaling-service

# RUN apt-get upgrade -y
# RUN apt-get update 
# RUN apt-get install -y golang-go 
RUN cd "/opt/niceice/p2p-signaling-service"
RUN go env -w GOPROXY=https://goproxy.cn,direct
CMD [ "go", "run", "cmd/server/main.go" ]

EXPOSE 80
EXPOSE 443