// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Chat struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Members     []*User    `json:"members"`
	LastMessage *Message   `json:"lastMessage"`
	Messages    []*Message `json:"messages"`
}

type ChatMessage struct {
	ID      string   `json:"id"`
	Message *Message `json:"message"`
}

type Message struct {
	ID     string  `json:"id"`
	Text   *string `json:"text"`
	Sender *User   `json:"sender"`
	Date   string  `json:"date"`
}

type User struct {
	ID string `json:"id"`
}
