// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Chat struct {
	ID          string   `json:"id"`
	Members     []*User  `json:"members"`
	Name        *string  `json:"name"`
	LastMessage *Message `json:"lastMessage"`
}

type Message struct {
	ID      string `json:"id"`
	Content string `json:"content"`
	Sender  *User  `json:"sender"`
	Date    string `json:"date"`
}

type NewChatMessage struct {
	ID      string   `json:"id"`
	Message *Message `json:"message"`
}

type User struct {
	ID string `json:"id"`
}
