
FROM node

ENV APP_PATH=/opt/niceice/pubsub-service
WORKDIR $APP_PATH

COPY ./service/. /opt/niceice/pubsub-service

RUN apt-get upgrade -y
RUN apt-get update 
RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN cd /opt/niceice/pubsub-service/
RUN npm install
# RUN npm install express express-graphql graphql mongoose jsonwebtoken sha256 express-jwt js-md5 merge-json apollo-server apollo-server-express  graphql-subscriptions subscriptions-transport-ws @graphql-tools/schema --save
CMD [ "node", "/opt/niceice/pubsub-service/main.js" ]

EXPOSE 80
EXPOSE 443