apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfu-service
spec:
  selector:
    matchLabels:
      app: sfu-service
  replicas: 1 
  template:
    metadata:
      labels:
        app: sfu-service
    spec:
      containers:
      - name: sfu-service
        image: registry.cn-shanghai.aliyuncs.com/niceice/sfu-service
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4443
      imagePullSecrets:
      - name: aliyun-credentials-sh
