apiVersion: v1
kind: Service
metadata:
  name: sfu-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 4443
    protocol: TCP
    targetPort: 4443
  selector:
    app: sfu-service
  sessionAffinity: None
  type: NodePort

